### ISSUE TITLE
Add a troubleshoot target

### ISSUE THREAD

**Issue by kirb** [kirb/theos#13]
Should look something like (pseudocode-ish):

``` make
ifeq (has ghost,1)
make clean all messages=yes color=no | ghost - ansi -x 24h
else
error "You need ghost.sh. Try curl https://ghostbin.com/ghost.sh -o /usr/local/bin/ghost; chmod +x /usr/local/bin/ghost."
endif
```

**Comment by uroboro** [comment]
Less pseudocode-ish:

GHOST = $(shell which ghost)
...
ifneq ($(GHOST),)
make clean all messages=yes color=no | $(GHOST) - ansi -x 24h
else
$(error "You need ghost.sh. Try curl https://ghostbin.com/ghost.sh -o /usr/local/bin/ghost; chmod +x /usr/local/bin/ghost.")
endif

**Comment by kirb** [comment]
:+1: (ew, old emoji)

**Comment by kirb** [comment]
Done in 2550fd8
