### ISSUE TITLE
FORRELEASE=1 does not work to disable debug builds

### ISSUE THREAD

**Issue by Aehmlo** [kirb/theos#3]
In the README for this repository, it says one can "use make DEBUG=0 or FORRELEASE=1 to build without debug." However, `make package FORRELEASE=1` does not properly disable debug builds; only `DEBUG=0` and `FINALPACKAGE=1` seem to do that. (Perhaps `FORRELEASE` was simply renamed to `FINALPACKAGE`? GitHub won't let me search a fork and I can't be bothered to wrestle with git locally.)

**Comment by kirb** [comment]
We worked this out privately, but for anyone else's reference, it's `FOR_RELEASE`, with an underscore. `FINALPACKAGE` is an alias.
