### ISSUE TITLE
Tweak Packaged Properly But Cant Find Generated dylib 

### ISSUE THREAD

**Issue by neoighodaro** [kirb/theos#6]
I created a test Tweak and tried to run it in the iOS simulator using [this tutorial](https://gist.github.com/friggog/03a2483b8acb9abdcd34). However I noticed, there are no generated dylibs for the tweak. Did I miss something?

**Comment by kirb** [comment]
Hard to give you an answer because you've provided almost no information. What is in `.theos/obj`? You should have `.theos/obj/debug/Blah.dylib`, of course assuming the compile was successful. If the dylib is built by a subproject, look in there instead of the root project.

**Comment by kirb** [comment]
Closing due to lack of response.
