### ISSUE TITLE
make update-theos fails

### ISSUE THREAD

**Issue by jithatsonei** [kirb/theos#8]
When attempting to use the command update theos on KUbuntu 15.04 the script will fail with the error "/bin/sh: 1:[[: Not found." The code that seems to cause this issue is commit 60119ae5a73ea828283650717a3b04ecf314bbc8

The file in question is located in $THEOS/makefiles/master/rules.mk and the line the code seems to fail is at line 121. A basic workaround is to just delete line 121-124.

**Comment by kirb** [comment]
Somehow that briefly worked… don't know why, but `[` is going to be a safer bet anyway. Thanks for reporting.

**Comment by DHowett** [comment]
Ubuntu made the shit decision to use `dash`, where `[[`is a bashism!

**Comment by jithatsonei** [comment]
![image](https://cloud.githubusercontent.com/assets/12538482/10582399/5325673e-764d-11e5-8023-b2bc352f6c66.png)
And then there are abunch of distributions listed above based on Ubuntu so :P

**Comment by kirb** [comment]
…Considering that, then, 47cbd45 now forces bash as the $SHELL.
