### ISSUE TITLE
clang error when building preference bundles

### ISSUE THREAD

**Issue by merdok** [kirb/theos#9]
Hi, 

i am getting the following error when i am building a preference bundle on El Capitan with the latest SDK and xCode:

```
clang: error: invalid arch name '-arch -F/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.0.sdk/System/Library/PrivateFrameworks'
```

Is this a bug or am I making something wrong?

Exppect that I am getting this warning:

```
ld: warning: directory not found for option '-L/usr/local/lib'
```

To fix that warning i had to create an empty dir in that location.

**Comment by kirb** [comment]
The first error is from makedeps. If you don't have build rules in your makefile for a file that's `#include`/`#import`ed into another file, you aren't using makedeps and can ignore it. It is indeed a bug in Theos, sorry about that.

I don't have an answer about the second one, unfortunately. It would be best for you to paste all makefiles in your project here.

**Comment by merdok** [comment]
Will you fix the clang errors? I have noticed that i can ignore them when i use GO_EASY_ON_ME = 1, but i feel more comfortable if my packages build without any warning or errors :)

The second warning is gone after i created the directory /usr/local/lib 
None of my makefiles has any references to the path in the warning. That is the strange about that. On DHowett's theos i didn't get the warning.

**Comment by kirb** [comment]
Yes, haven't gotten around to it yet. However be aware that these aren't fatal; makedeps errors are ignored. If you definitely can't get past makedeps errors without using GO_EASY_ON_ME, there might be something wrong with your setup?

Can you reproduce the same linker warning with Ryan Petrich's Theos? https://github.com/rpetrich/theos

**Comment by merdok** [comment]
With GO_EASY_ON_ME i can build successfully :) This is just a cosmetic issue.

With Ryan Petrich's Theos i didn't get the warning too even that i removed the directory. The strange about that is that the warning also is gone now with your theos even that i removed the directory...

**Comment by kirb** [comment]
If you updated Theos in the past few days, I fixed the makedeps issues, although I don't know what I might have done to cause or fix the linker error.

So to be sure, everything is working now?

**Comment by merdok** [comment]
Yes, that has fixed the warnings :) Now i have a clean build log! Thanks!
